### ISSUE TITLE
Does this duplicate the existing script tasks?

### ISSUE THREAD

**Issue by xiphoid24** [cloudpups/authenticated-scripts#4]
Does this extension make use of the existing Azure DevOps script tasks or does it duplicate the code?

I really like this extension and think it would be very useful. My only concern is if it is duplicating the existing Azure DevOps tasks.
If the existing Azure DevOps PowerShell and Script tasks get updated will this extension get those updates or will we have to wait for this extension to update it's code to match what the Azure DevOps tasks are?

**Comment by JoshuaTheMiller** [comment]
For all intents and purposes, I would consider this extension _completely separate_ from the built-in Azure DevOps script tasks at this point in time.

With that being said, I/we are open to accepting modifications to this extension so that it would simply be a wrapper around the existing tasks (thus getting those updates!) 🙂

Not that this is a blocker, but do you have any thoughts on what potential updates you think would be made to those tasks?

**Comment by xiphoid24** [comment]
Thanks for the quick response @JoshuaTheMiller. 

I am not sure what updates there would be. At this point those tasks are probably not going to change. I was just thinking if hypothetically a bug was found with on of those tasks the needed fixed.

I do not have much experience with Azure DevOps extensions. Odds are I wouldn't know how to go about making a wrapper for those tasks, at least not any time soon. If I get time I may look into the ability to call existing tasks from a custom task.
When that time comes I'll make a PR 😉

**Comment by koosg** [comment]
So, close the issue then?

**Comment by xiphoid24** [comment]
Yes this can be closed. Sorry for not getting around to it sooner.

**Comment by JoshuaTheMiller** [comment]
No worries, @gregpechiro! I wanted to make sure I/we actually solved your problem. 

One of my biggest annoyances with open source projects is when maintainers prematurely close Issues, and I want to not add to that problem 🙂
